name: Deploy app

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2

     #- name: Use Node.js
     #  uses: actions/setup-node@v1
     #  with:
     #    node-version: '18.x'

     #- name: Install dependencies
     #   run: yarn install

      - name: Deploy to DigitalOcean
        uses: digitalocean/app_action@main
        with:
          app_name: echo-speaks-server
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
